<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Phonebook - Home</title>
  <link rel="stylesheet" href="styles.css">
  <link rel="shortcut icon" type="image/x-icon" href="assets/favicon.ico" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
  <main>

    <?php include "templates/header.php";?>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="index.phtml">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="add-contact.phtml">Add Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="delete-contact.phtml">Delete Contact</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="search-results.phtml" method="POST">
          <input class="form-control mr-sm-2" type="search" name="search" placeholder="Search Contacts"
            aria-label="Search" required>
          <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <div class="all-contacts">
      <?php include "all-db-contacts.php";?>
    </div>

    <?php include "templates/footer.php";?>

  </main>

  <?php include "templates/bootstrap.php";?>

</body>

</html>